In [278]:
# Import packages
import csv # Read in case parameters and write out solutions
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [279]:
def gauss_seidel(N,A,x,b):
    # Solve Ax = b iteratively using Gauss seidel
    print('N:',N)# N: number of variables
    print('A:',A) # coefficient matrix, NxN size (square matrix)
    # x: variables, Nx1 size (column vector)

    # Solver Parameters
    tol = 1E-6 # tolerance to determining stopping point of scheme
    res = 1.0 # residual (initially greater than the tolerance
    max_iter = 100 # max iterations (so it doesn't go forever)
    k = 0 # iteration counter

    # self.p[2:N-1] = zeros(N-2,1) # initial guess for cell centers

    ## Iteration Loop
    while ((res>tol)and(k<max_iter)):
        x_prev = np.copy(x)# previous iteration (copy to avoid using same mem loc)
        for i in range(0,N):
            xi = b[i]
            for j in range(0,N):
                if i!=j: xi -= A[i][j]*x[j] #;  print('J:',i,j,A[i][j],xi,x[j])
            x[i] = xi/A[i][i]
            # print('I:',i,xi,b[i],A[i][i])
        res = sum(abs(x-x_prev)) # L2 norm of p_diff
        k += 1 # increase iteration count
        print('Iter, Res, x',k,res,x)
        
    print('Iteration Complete')
    return [x,k,res]

In [296]:
def succ_OR(N,A,x,b):
    # Solve Ax = b iteratively using successive overrelaxation
    # N: number of variables
    # A: coefficient matrix, NxN size (square matrix)
    # x: variables, Nx1 size (column vector)

    # Solver Parameters
    tol = 1E-6 # tolerance to determining stopping point of scheme
    res = np.array([1.0],dtype=float) # residual (initially greater than the tolerance
    max_iter = 100 # max iterations (so it doesn't go forever)
    k = 0 # iteration counter
    omega = 1.1 # relaxation factor (for Gauss-Seidel, always 1)
    
    # self.p[2:N-1] = zeros(N-2,1) # initial guess for cell centers

    ## Iteration Loop
    while ((res[k]>tol)and(k<max_iter)):
        x_prev = np.copy(x)# previous iteration (copy to avoid using same mem loc)
        for i in range(0,N):
            xi = b[i]
            for j in range(0,N):
                if i!=j: xi -= A[i][j]*x[j] #;  print('J:',i,j,A[i][j],xi,x[j])
            x[i] = omega*xi/A[i][i] + (1.0-omega)*x_prev[i]
            # print('I:',i,xi,b[i],A[i][i])
        res = np.append(res,[sum(abs(x-x_prev))]) # L2 norm of p_diff
        k += 1 # increase iteration count
        print('Iter, Res, x',k,res[k-1],x)
        
    print('Iteration Complete')
    df = pd.DataFrame(res,columns=['residual'])
    df.to_csv('res.csv',sep='\t')
    return [x,k,res[k-1]]

In [287]:
N = 4; x0 = np.zeros(N,dtype=float) # initialize
A = np.array([[1,1,1,1],[2,-5,3,2],[0,-3,1,-1],[1,0,-2,3]],dtype=float)
b = np.array([25,0,6,-8],dtype=float)
x0[0] = 491.0/7.0; x0[1] = 71.0/14.0; x0[2] = -29.0/2.0; x0[3] = -250.0/7.0

In [288]:
[x,k,res] = gauss_seidel(N,A,x0,b)

N: 4
A: [[ 1.  1.  1.  1.]
 [ 2. -5.  3.  2.]
 [ 0. -3.  1. -1.]
 [ 1.  0. -2.  3.]]
Iter, Res, x 1 8.881784197001252e-15 [ 70.14285714   5.07142857 -14.5        -35.71428571]
Iteration Complete


In [289]:
x0 = np.ones(N,dtype=float)
A = np.random.randint(1,4,size=[N,N]).astype(float)
A = (A+A.transpose())+(np.eye(N)*7.0)
A

array([[11.,  4.,  6.,  6.],
       [ 4., 13.,  4.,  3.],
       [ 6.,  4.,  9.,  4.],
       [ 6.,  3.,  4.,  9.]])

In [290]:
[x,k,res] = gauss_seidel(N,A,x0,b)

N: 4
A: [[11.  4.  6.  6.]
 [ 4. 13.  4.  3.]
 [ 6.  4.  9.  4.]
 [ 6.  3.  4.  9.]]
Iter, Res, x 1 5.127428127428128 [ 0.81818182 -0.79020979  0.02797203 -1.18337218]
Iter, Res, x 2 4.408429790973173 [ 3.19029455 -0.71714998 -0.61551985 -2.50313755]
Iter, Res, x 3 2.087807483280397 [ 4.23459494 -0.53591444 -0.80570685 -3.1752221 ]
Iter, Res, x 4 0.7988053713287568 [ 4.63902104 -0.44673773 -0.81625411 -3.46987741]
Iter, Res, x 5 0.304229402872741 [ 4.77306727 -0.41674003 -0.78799265 -3.58180144]
Iter, Res, x 6 0.10074700303670181 [ 4.80779315 -0.41029213 -0.76426496 -3.61764696]
Iter, Res, x 7 0.02645964690156727 [ 4.81205819 -0.41063323 -0.75102537 -3.62626088]
Iter, Res, x 8 0.010403494740520436 [ 4.80965913 -0.41198095 -0.74499861 -3.62689083]
Iter, Res, x 9 0.006661327941350215 [ 4.8072055  -0.412935   -0.74265885 -3.62597695]
Iter, Res, x 10 0.003459498045298881 [ 4.80577771 -0.41342651 -0.74189471 -3.62520088]
Iter, Res, x 11 0.0014886162694484062 [ 4.80511632 -0.41363722 -0.7417

In [297]:
x0 = np.ones(N,dtype=float)
[x,k,res] = succ_OR(N,A,x0,b)

Iter, Res, x 1 1.0 [ 0.8        -0.96307692  0.02861538 -1.32530598]
Iter, Res, x 2 5.459767521367522 [ 3.58324513 -0.78974435 -0.86321669 -2.7613703 ]
Iter, Res, x 3 5.284474095336241 [ 4.63232542 -0.49576067 -0.9850085  -3.43534077]
Iter, Res, x 4 2.138826237599747 [ 4.88728129 -0.39914514 -0.87753454 -3.64287987]
Iter, Res, x 5 0.6665844640461172 [ 4.88317858 -0.39111088 -0.78773758 -3.66596394]
Iter, Res, x 6 0.1250179982840932 [ 4.84034741 -0.40195062 -0.74872278 -3.64734534]
Iter, Res, x 7 0.11130430783628431 [ 4.81438638 -0.41001111 -0.73874791 -3.6320902 ]
Iter, Res, x 8 0.05925151448010563 [ 4.80506867 -0.41329994 -0.73876261 -3.62556964]
Iter, Res, x 9 0.019141793648568772 [ 4.80341246 -0.41406074 -0.74036247 -3.62394603]
Iter, Res, x 10 0.005640479970885903 [ 4.80386815 -0.41400955 -0.74135545 -3.62397588]
Iter, Res, x 11 0.0015296999439569081 [ 4.8044158  -0.41385636 -0.74171806 -3.62425339]
Iter, Res, x 12 0.0013409590336283528 [ 4.80468383 -0.41376923 -0.74178528 -3.62442

In [315]:
s = np.array([[2,3,4,4]])
s = np.append(s,[[2,4,3,6]],axis=0)

In [316]:
s

array([[2, 3, 4, 4],
       [2, 4, 3, 6]])

In [331]:
t = np.array([1])#,[2]])
my_array = np.arange(6).reshape(3, 2)
print(f"My array shape is: \n {my_array.shape}")

my_expanded_array = my_array[:, np.newaxis, :, np.newaxis]
print(f"My expanded array shape is: \n {my_expanded_array.shape}")

t2 = t[:,np.newaxis]
print(t2,t2.shape)

My array shape is: 
 (3, 2)
My expanded array shape is: 
 (3, 1, 2, 1)
[[1]] (1, 1)


In [319]:
np.append(t,s,axis=1)

array([[1, 2, 3, 4, 4],
       [2, 2, 4, 3, 6]])

In [323]:
t.shape

(2,)